USE ROLE SYSADMIN;
CREATE SCHEMA SNOWFLAKE_CONSENT_DEMO.ORG_SHARED_VIEWS;

CREATE SECURE VIEW SNOWFLAKE_CONSENT_DEMO.ORG_SHARED_VIEWS.MOONRAKER_USER_CONSENT
AS SELECT
    CONSENT_CDP_DEMO.CONSENT_DATA.USER_CONSENT.ORGANIZATION_CODE,
    CONSENT_CDP_DEMO.CONSENT_DATA.USER_CONSENT.IDENTITY_SPACE,
    CONSENT_CDP_DEMO.CONSENT_DATA.USER_CONSENT.IDENTITY_VALUE,
    CONSENT_CDP_DEMO.CONSENT_DATA.USER_CONSENT.PURPOSE,
    CONSENT_CDP_DEMO.CONSENT_DATA.USER_CONSENT.CONSENT,
    CONSENT_CDP_DEMO.CONSENT_DATA.USER_CONSENT.RECORDED_AT
FROM CONSENT_CDP_DEMO.CONSENT_DATA.USER_CONSENT
WHERE ORGANIZATION_CODE = 'MOONRAKER';

USE ROLE ACCOUNTADMIN;
CREATE SHARE MOONRAKER_SHARE;

GRANT USAGE ON DATABASE CONSENT_CDP_DEMO TO SHARE MOONRAKER_SHARE;
GRANT USAGE ON SCHEMA CONSENT_CDP_DEMO.CONSENT_DATA TO SHARE MOONRAKER_SHARE;
GRANT USAGE ON SCHEMA CONSENT_CDP_DEMO.ORG_SHARED_VIEWS TO SHARE MOONRAKER_SHARE;
GRANT SELECT ON VIEW CONSENT_CDP_DEMO.ORG_SHARED_VIEWS.MOONRAKER_USER_CONSENT TO SHARE MOONRAKER_SHARE;

ALTER SHARE MOONRAKER_SHARE ADD ACCOUNTS=<MOONRAKER_SNOWFLAKE_ACCOUNT>;
