USE ROLE ACCOUNTADMIN;

--  Define a Snowflake Role and User for each Purpose
-- create role and user for each purpose - ANALYTICS, PERSONALIZATION, TARGETED_ADVERTISING, DATA_SALES, MARKETING_EMAIL
CREATE ROLE ANALYTICS;
CREATE USER ANALYTICS_USER PASSWORD='Ch1ng5m5!42' DEFAULT_ROLE = ANALYTICS MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ANALYTICS TO USER ANALYTICS_USER;

CREATE ROLE PERSONALIZATION;
CREATE USER PERSONALIZATION_USER PASSWORD='Ch1ng5m5!42' DEFAULT_ROLE = PERSONALIZATION MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE PERSONALIZATION TO USER PERSONALIZATION_USER;

CREATE ROLE TARGETED_ADVERTISING;
CREATE USER TARGETED_ADVERTISING_USER PASSWORD='Ch1ng5m5!42' DEFAULT_ROLE = TARGETED_ADVERTISING     MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE TARGETED_ADVERTISING TO USER TARGETED_ADVERTISING_USER;


-- Create role that will own the row access policy
-- This will prevent runtime policy evaluation from being executed as ACCOUNTADMIN
CREATE ROLE PURPOSE_POLICY_ROLE;
CREATE USER PURPOSE_POLICY_USER PASSWORD='Ch1ng5m5!42'
    DEFAULT_ROLE = PURPOSE_POLICY_ROLE MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE PURPOSE_POLICY_ROLE TO USER PURPOSE_POLICY_USER;
