USE ROLE ACCOUNTADMIN;

-- create role and user for each purpose - ANALYTICS, PERSONALIZATION, TARGETED_ADVERTISING, DATA_SALES, MARKETING_EMAIL
CREATE ROLE ANALYTICS;
CREATE USER ANALYTICS_USER PASSWORD='Ch1ng5m5!42' DEFAULT_ROLE = ANALYTICS MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE ANALYTICS TO USER ANALYTICS_USER;

-- create role that will own the row access policy
-- will prevent runtime policy evaluation from being executed as ACCOUNTADMIN
CREATE ROLE PURPOSE_POLICY_ROLE;
CREATE USER PURPOSE_POLICY_USER PASSWORD='Ch1ng5m5!42'
    DEFAULT_ROLE = PURPOSE_POLICY_ROLE MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE PURPOSE_POLICY_ROLE TO USER PURPOSE_POLICY_USER;
